name: Astra-toolbox

on: [push, pull_request]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: environment-dev.yml
          python-version: 3.8
          auto-activate-base: false
      - name: Install pylops
        run: |
          pip install .
      - name: Test with pytest
        run: |
          pytest
